gateways:
  local:
    connection:
      type: duckdb
      database: /Users/david/bluesky-data/bluesky.duckdb

default_gateway: local

model_defaults:
  dialect: duckdb
  start: 2024-12-03

variables:
  bsky_actor: {{ env_var('bsky_actor') }}